# Generated by Django 5.2.4 on 2025-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_date_of_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите ID сессии", max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
    ]
