# Generated by Django 5.2.4 on 2025-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link_for_pay",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
