# Generated by Django 5.2.4 on 2025-08-01 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_for_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now, verbose_name="Дата и время последнего входа"
            ),
            preserve_default=False,
        ),
    ]
