# Generated by Django 5.2.4 on 2025-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на видео исключительно на youtube, проходит валидация",
                max_length=300,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
